version: '3.8'

services:
  lionkapp:
    image: ghcr.io/lionk-framework/lionkapp:latest
    privileged: true # Required to access GPIO
    user: root # Run as root to access GPIO
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/mem:/dev/mem"
      - "/dev/ttyAMA0:/dev/ttyAMA0"
      - "/dev/ttyS0:/dev/ttyS0"
    volumes:
      - /sys:/sys # Give the full access to sys folder
      - ./config:/app/config
      - ./plugins:/app/plugins
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp
      - ./keys:/root/.aspnet/DataProtection-Keys
    ports:
      - "5001:5001"
    restart: always # can be removed if you don't want to restart the container